import {listPosts} from '@/lib/store';
import {catalog} from '@/lib/hub';
import {THEMES,themeName} from '@/lib/types';
import {PostCard} from './cards';
export async function Webzine({params,home=false}:{params:Record<string,string|undefined>;home?:boolean}){
 const theme=THEMES.some(t=>t.id===params.theme)?params.theme:undefined;const q=(params.q||'').slice(0,100);const page=Math.max(1,Number(params.page)||1);let data;
 try{data=await listPosts({theme,q,page});}catch{return <main className="shell"><div className="error-panel"><h1>웹진을 불러오지 못했습니다.</h1><p>저장소 연결을 확인한 뒤 다시 시도해 주세요.</p><a className="button" href="/blog">다시 불러오기</a></div></main>;}
 const images=home&&!data.total?await catalog().then(a=>a.slice(0,3)).catch(()=>[]):[];
 const base=home?'/':'/blog';const link=(p:number)=>base+'?'+new URLSearchParams({...(theme?{theme}:{}),...(q?{q}:{}),page:String(p)});
 return <main className="shell"><section className={'editorial-intro '+(home?'':'compact')}><div className="intro-copy"><span className="eyebrow"><span className="tiny-line"/> THE IMAGE-LED JOURNAL</span><h1>이미지에 담긴 취향,<br/>이야기가 되다<span className="blue-dot">.</span></h1><p>여행의 풍경부터 일상의 작은 발견까지.<br/>좋은 이미지와 함께 읽는 새로운 시선.</p><div className="intro-actions"><a className="button blue" href="/studio">새 이야기 만들기</a><span>누구나 편하게 읽는 공개 웹진</span></div></div>{home&&<div className="intro-visual">{data.posts[0]?<PostCard post={data.posts[0]}/>:images.length?<><img className="hero-image" src={images[0].url} alt={images[0].title}/><div className="visual-label"><span>FROM THE IMAGE HUB</span><strong>{images[0].title}</strong></div><div className="floating-label"><b>IMAGE → STORY</b><span>취향이 이야기가 되는 곳</span></div></>:<div className="type-art"><span>IMAGE.</span><span>STORY.</span><span>STUDIO<span className="blue-dot">4</span></span></div>}</div>}</section><section className="journal-section"><div className="section-heading"><div><span className="eyebrow">THE JOURNAL</span><h2>{theme?themeName(theme):'새로운 이야기'} <span className="count">{data.total}</span></h2></div><form className="search" action={base}>{theme&&<input type="hidden" name="theme" value={theme}/>}<label htmlFor="journal-search" className="sr-only">글 검색</label><input id="journal-search" name="q" defaultValue={q} placeholder="읽고 싶은 이야기를 검색하세요"/><button aria-label="검색">⌕</button></form></div><div className="filter-row"><a className={!theme?'filter active':'filter'} href={base+(q?'?q='+encodeURIComponent(q):'')}>전체</a>{THEMES.map(t=><a key={t.id} className={theme===t.id?'filter active':'filter'} href={base+'?'+new URLSearchParams({theme:t.id,...(q?{q}:{})})}>{t.name}</a>)}</div>{data.posts.length?<div className="post-grid">{data.posts.map(p=><PostCard key={p.id} post={p}/>)}</div>:<div className="empty-journal"><span className="empty-symbol">✦</span><h3>{q?'검색 결과가 없습니다.':'첫 번째 이야기를 기다리고 있어요.'}</h3><p>{q?'다른 검색어나 테마로 찾아보세요.':'테마를 고르면 주제와 이미지를 연결해 새로운 글을 완성합니다.'}</p><a className="button dark" href={q?base:'/studio'}>{q?'전체 글 보기':'제작 스튜디오 열기'}</a></div>}{data.total>12&&<nav className="pagination" aria-label="글 목록 페이지">{page>1&&<a href={link(page-1)}>이전</a>}{Array.from({length:Math.ceil(data.total/12)},(_,i)=><a key={i} className={page===i+1?'active':''} href={link(i+1)} aria-current={page===i+1?'page':undefined}>{i+1}</a>)}{page<Math.ceil(data.total/12)&&<a href={link(page+1)}>다음</a>}</nav>}</section><section className="studio-strip"><div><span className="eyebrow">YOUR NEXT STORY</span><h2>사진을 고르는 고민까지,<br/>스튜디오에 맡겨보세요.</h2></div><a className="button blue" href="/studio">테마로 시작하기</a></section></main>;
}
